// Generate the favicon + PWA icon PNGs from the canonical logo.svg.
//
//   favicon-32.png                Browser tab fallback for clients that don't
//                                 honor SVG favicons (older Safari, iOS).
//   favicon-16.png                Same, smaller. Most browsers pick whichever
//                                 they need from the <link rel="icon"> set.
//   apple-touch-icon.png          iOS home screen — the canonical filename
//                                 iOS auto-discovers when not declared in
//                                 the link tags.
//   apple-touch-icon-180x180.png  iOS home screen, explicit-size variant.
//                                 Kept identical to apple-touch-icon.png for
//                                 belt + suspenders.
//   icon-192.png                  PWA install (Android, Chrome) — transparent.
//   icon-512.png                  PWA splash — transparent.
//   icon-512-maskable.png         Android adaptive icon — opaque, logo in
//                                 the safe zone (center 80%).
//
// Run with: node scripts/generate-icons.mjs
//
// One-off — output is committed to public/ so we don't have to install sharp
// in CI just to rebuild icons.

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import sharp from 'sharp';

const ROOT = resolve(import.meta.dirname, '..');
const SRC = resolve(ROOT, 'public/logo.svg');
const OUT_DIR = resolve(ROOT, 'public');

// Apple's home screen icons composite onto whatever wallpaper the user has,
// so a white tile reads cleanly on every wallpaper (light or dark) and lets
// the green-man artwork pop against the bright field.
const APPLE_ICON_BG = '#FFFFFF';
// Android maskable icons get cropped into circles / squircles / teardrops by
// the system, so the visible bg is whatever fills the safe-zone padding.
// Keep this matching the default Moss --color-bg so an Android adaptive
// icon set against a dark drawer still feels like the app.
const MASKABLE_ICON_BG = '#121212';

const svg = readFileSync(SRC);

async function transparent(size, file) {
  await sharp(svg, { density: 384 })
    .resize(size, size, {
      fit: 'contain',
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .png()
    .toFile(resolve(OUT_DIR, file));
  console.log(`wrote ${file} (${size}×${size}, transparent)`);
}

/**
 * Logo painted at `inset` % of canvas, centered, on an opaque background.
 * Used for iOS home-screen icons (iOS ignores transparency and shows the
 * underlying home screen instead) and Android maskable icons (cropped into
 * arbitrary silhouettes by the system).
 */
async function opaque(size, file, innerRatio, bgColor) {
  const inner = Math.round(size * innerRatio);
  const inset = Math.round((size - inner) / 2);
  const logoPng = await sharp(svg, { density: 384 })
    .resize(inner, inner, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer();
  await sharp({
    create: {
      width: size,
      height: size,
      channels: 4,
      background: bgColor,
    },
  })
    .composite([{ input: logoPng, top: inset, left: inset }])
    .png()
    .toFile(resolve(OUT_DIR, file));
  console.log(`wrote ${file} (${size}×${size}, opaque ${bgColor} @ ${Math.round(innerRatio * 100)}% safe zone)`);
}

// Browser tab favicons (transparent — modern browsers pick the SVG; PNGs are
// fallbacks for the ones that don't render SVG favicons).
await transparent(16, 'favicon-16.png');
await transparent(32, 'favicon-32.png');

// iOS home-screen icons (white bg, ~92% safe zone — small inset so the
// rounded mask iOS applies doesn't shave off the logo's edges).
await opaque(180, 'apple-touch-icon.png', 0.92, APPLE_ICON_BG);
await opaque(180, 'apple-touch-icon-180x180.png', 0.92, APPLE_ICON_BG);

// PWA icons (Android / installable).
await transparent(192, 'icon-192.png');
await transparent(512, 'icon-512.png');
// Maskable: 80% safe zone — Android can crop the outer 20% into any shape.
await opaque(512, 'icon-512-maskable.png', 0.8, MASKABLE_ICON_BG);

writeFileSync(
  resolve(OUT_DIR, 'icons.README.txt'),
  'Generated by scripts/generate-icons.mjs from logo.svg. Re-run after updating logo.svg.\n',
);
console.log('done');
