// Generate the PWA icon PNGs from the canonical logo.svg.
//
//   apple-touch-icon-180x180.png  iOS home screen
//   icon-192.png                  PWA install (Android, Chrome)
//   icon-512.png                  PWA splash
//   icon-512-maskable.png         Android adaptive icon — opaque bg, logo
//                                 inside the safe zone (center 80%) so the
//                                 system can crop it to any silhouette
//                                 (circle, squircle, teardrop, square)
//                                 without clipping the artwork.
//
// Run with: node scripts/generate-icons.mjs
//
// One-off — output is committed to public/ so we don't have to install sharp
// in CI just to rebuild icons.

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import sharp from 'sharp';

const ROOT = resolve(import.meta.dirname, '..');
const SRC = resolve(ROOT, 'public/logo.svg');
const OUT_DIR = resolve(ROOT, 'public');

// Maskable bg matches the default Moss theme's --color-bg so the icon looks
// integrated with our app shell. Change this if the default theme ever shifts.
const MASKABLE_BG = '#121212';

const svg = readFileSync(SRC);

async function transparent(size, file) {
  await sharp(svg, { density: 384 })
    .resize(size, size, {
      fit: 'contain',
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .png()
    .toFile(resolve(OUT_DIR, file));
  console.log(`wrote ${file} (${size}×${size}, transparent)`);
}

async function maskable(size, file) {
  // Logo painted at 80% of canvas, centered, on an opaque background. Android
  // mask shapes only ever clip the outer 20% — anything inside the safe zone
  // is guaranteed visible.
  const inner = Math.round(size * 0.8);
  const inset = Math.round((size - inner) / 2);
  const logoPng = await sharp(svg, { density: 384 })
    .resize(inner, inner, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer();
  await sharp({
    create: {
      width: size,
      height: size,
      channels: 4,
      background: MASKABLE_BG,
    },
  })
    .composite([{ input: logoPng, top: inset, left: inset }])
    .png()
    .toFile(resolve(OUT_DIR, file));
  console.log(`wrote ${file} (${size}×${size}, maskable on ${MASKABLE_BG})`);
}

await transparent(180, 'apple-touch-icon-180x180.png');
await transparent(192, 'icon-192.png');
await transparent(512, 'icon-512.png');
await maskable(512, 'icon-512-maskable.png');

// Drop a sentinel so anyone reading public/ knows where the PNGs came from.
writeFileSync(
  resolve(OUT_DIR, 'icons.README.txt'),
  'Generated by scripts/generate-icons.mjs from logo.svg. Re-run after updating logo.svg.\n',
);
console.log('done');
